# fly.toml app configuration file generated for aged-sound-1664 on 2023-06-20T01:15:09-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "aged-sound-1664"
primary_region = "sea"

[env]
PORT = 3000

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
